server:
  port: 10010

spring:
  application:
    name: zuul-proxy

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
    registry-fetch-interval-seconds: 5

zuul:
  routes: #服务器配置路由
    feign-server:
      path: /feign/**
  prefix: /api #add prefix for url
  sensitive-headers:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
