server:
  port: 8086 #开启的端口
spring:
  application:
    name: user-server #服务的名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/ #注册到eureka的地址
    registry-fetch-interval-seconds: 5  #eureka client间隔5s去拉取服务注册信息
