server:
  port: 8087 #开启的端口
spring:
  application:
    name: feign-server #服务的名称
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/ #注册到eureka的地址
    registry-fetch-interval-seconds: 5  #eureka client间隔5s去拉取服务注册信息
